az-configuration:
- name: us-east-1a
- name: us-east-1b
- name: us-east-1c
network-assignment:
  network:
    name: infrastructure
  other_availability_zones: []
  singleton_availability_zone:
    name: us-east-1a
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: infrastructure
    subnets:
    - iaas_identifier: ((infrastructure_subnet_0))
      cidr: 10.0.16.0/28
      dns: 10.0.0.2
      gateway: 10.0.16.1
      reserved_ip_ranges: 10.0.16.0-10.0.16.4
      availability_zone_names:
      - us-east-1a
    - iaas_identifier: ((infrastructure_subnet_1))
      cidr: 10.0.16.16/28
      dns: 10.0.0.2
      gateway: 10.0.16.17
      reserved_ip_ranges: 10.0.16.16-10.0.16.20
      availability_zone_names:
      - us-east-1b
    - iaas_identifier: ((infrastructure_subnet_2))
      cidr: 10.0.16.32/28
      dns: 10.0.0.2
      gateway: 10.0.16.33
      reserved_ip_ranges: 10.0.16.32-10.0.16.36
      availability_zone_names:
      - us-east-1c
  - name: control-plane
    subnets:
    - iaas_identifier: ((control-plane_subnet_0))
      cidr: 10.0.4.0/26
      dns: 10.0.0.2
      gateway: 10.0.4.1
      reserved_ip_ranges: 10.0.4.0-10.0.4.4
      availability_zone_names:
      - us-east-1a
    - iaas_identifier: ((control-plane_subnet_1))
      cidr: 10.0.4.64/26
      dns: 10.0.0.2
      gateway: 10.0.4.65
      reserved_ip_ranges: 10.0.4.64-10.0.4.68
      availability_zone_names:
      - us-east-1b
    - iaas_identifier: ((control-plane_subnet_2))
      cidr: 10.0.4.128/26
      dns: 10.0.0.2
      gateway: 10.0.4.129
      reserved_ip_ranges: 10.0.4.128-10.0.4.132
      availability_zone_names:
      - us-east-1c
properties-configuration:
  iaas_configuration:
    access_key_id: ((ops_manager_iam_user_access_key))
    secret_access_key: ((ops_manager_iam_user_secret_key))
    security_group: ((vms_security_group_id))
    key_pair_name: ((ops_manager_ssh_public_key_name))
    ssh_private_key: ((ops_manager_ssh_private_key))
    region: us-east-1
  director_configuration:
    blobstore_type: s3
    bosh_recreate_on_next_deploy: false
    bosh_recreate_persistent_disks_on_next_deploy: false
    database_type: internal
    director_worker_count: 5
    hm_emailer_options:
      enabled: false
    hm_pager_duty_options:
      enabled: false
    identification_tags: {}
    job_configuration_on_tmpfs: false
    keep_unreachable_vms: false
    ntp_servers_string: ((ntp_servers))
    post_deploy_enabled: true
    resurrector_enabled: true
    retry_bosh_deploys: false
    s3_blobstore_options:
      bucket_name: ((ops_manager_bucket))
      endpoint: https://s3.us-east-1.amazonaws.com
      region: us-east-1
      signature_version: "4"
      access_key: ((ops_manager_iam_user_access_key))
      secret_key: ((ops_manager_iam_user_secret_key))
    skip_director_drain: false
  security_configuration:
    generate_vm_passwords: true
    opsmanager_root_ca_trusted_certs: true
  syslog_configuration:
    enabled: false
resource-configuration:
  compilation:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: false
  director:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: false
vmextensions-configuration:
  - name: control-plane-lb-security-groups
    cloud_properties:
      security_groups: ["control_plane_security_group", "vms_security_group"]
  - name: credhub-lb-cloud-properties
    cloud_properties:
      security_groups:
      - ((credhub_lb_security_group))
      - vms_security_group
      lb_target_groups:
      - ((credhub_lb_target_group))
  - name: uaa-lb-cloud-properties
    cloud_properties:
      security_groups:
      - ((uaa_lb_security_group))
      - vms_security_group
      lb_target_groups:
      - ((uaa_lb_target_group))
  - name: control-plane-lb-cloud-properties
    cloud_properties:
      security_groups:
      - ((web_lb_security_group))
      - vms_security_group
      lb_target_groups:
      - ((web_lb_target_group))